# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ded6597b205e0c258366e25cab1277cdc951578f6894299cc5333ded78bc8dd3e5c43289bfd2c9fd199f8e9268a21306ceca9d8af5eb6783aca085e6d9987033

test:
  secret_key_base: b1785c7b33541f66f028086b46737ad43088904946111dca78d4a2ca5dbfe6d24480f6d19577f70edfafe8b4784f82e83a0ae06012babe2a66300faa52f2fa8a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
